api/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from . import db
from .model import User, stat_weight

auth = Blueprint('auth', __name__)

global isLog
isLog = False

def isLogB(Log):
    Log = isLog
    return Log

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/login', methods=['POST'])
def login_POST():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) 

    login_user(user, remember=remember)

    return redirect(url_for('main.profile'))


@auth.route('/signup', methods= ['POST'])
def signup_POST():
    email = request.form.get('email')
    name = request.form.get('name')
    weight = request.form.get('weight')
    password = request.form.get('password')
    
    
    #checks password string to ensure its alpha numeric and between a certain amount of strings...
    pass_checker(password)


    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

    if user:      
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # creates a new user...

    new_user = User(email=email, name=name, weight = weight, password=generate_password_hash(password, method='sha256'))



    #AgentRambo00
    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()
    current_weight = stat_weight(Weight = weight, Stat_DATE = date.today())
    new_user.stat_weight.append(current_weight)
    db.session.add(current_weight)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth.route('/logout')
def logout():

    logout_user()
    isLog = False
    #return render_template('index.html', isLogin = isLog)
    return redirect(url_for('main.changeLog'))


def pass_checker(passw):
    plength = len(passw)

    #checks the length of the password...
    if plength < 5 or plength> 15:
        pcheck = False
        flash('There is either too few characters or far to many characters. Please enter password again...')
        return redirect(url_for('auth.signup'))
    
    #checks if the password has any speical characters in it...
    if passw.isalnum() == False:
        flash('There are special characters in this string. Please re-enter password...')
        return redirect(url_for('auth.signup'))

api/views.py
from flask import Blueprint, jsonify, request, render_template
from flask_login import login_required, current_user
from . import db
from .model import User, Food, Statistics, Exercise, stat_weight, daily_workout, logged_food
from datetime import datetime, date, timedelta
import re


    
# .open E:/PrimeFitness/api/database.db use this when testing out sqlite3... 
# sqlite3.exe is located in E:/sqlite3


main = Blueprint('main', __name__)

global isLog
global today
today = date.today()

isLog = False

@main.route('/')
def index():
    global isLog
    return render_template('index.html', isLogin= isLog)

@main.route('/main')
def changeLog():
    global isLog
    isLog = False
    return render_template('index.html', isLogin = isLog)

@main.route('/profile')
@login_required
def profile():
    global isLog
    isLog = True
    push_st_date = []
    combine_date_weight = {} 
    calories_dict = {}
    cal_consumed_list = {} 
    cal_expended_list = {}
    stat = Statistics.query.all()
    user_stat_weight = stat_weight.query.all()
    avg_BMR = 1600 
    weeklength = 7

    #gets the past 7 days of progess if there is any...
    for i in range(weeklength):
        pastdate = str(datetime.now() - timedelta(days = i))
        push_st_date.append(pastdate[0:10])

    #sorting list to to make sure the dates are in correct order from left-right...
    push_st_date.sort(reverse=False)
    
    #logging actual user weight into graphs...
    for userweight in  user_stat_weight:
        totalcal = 0
        for date in push_st_date:
            if current_user.id == userweight.fk_id and str(userweight.Stat_DATE) == date:
                combine_date_weight[date] = userweight.Weight
    
    #to get data for the calories...
    for x in stat:
        for date in push_st_date:
            if current_user.id == x.fk__UserID and str(x.stat_Date) == date:
                cal_consumed_list[str(x.stat_Date)] = x.Total_Calories_Consumed
                cal_expended_list[str(x.stat_Date)] = x.total_Calories_expended

    print(calories_dict)
    return render_template('profile.html', name = current_user, isLogin = isLog, labels = push_st_date, 
                points = combine_date_weight, calories_consumed_chart = cal_consumed_list,
                calories_expended_chart = cal_expended_list)

@main.route('/statistics', methods=['GET'])
@login_required
def statistics():
    global isLog
    push_st_date = []
    combine_date_weight = {} 
    calories_dict = {}
    cal_consumed_list = {} 
    cal_expended_list = {}
    stat = Statistics.query.all()
    user_stat_weight = stat_weight.query.all()
    avg_BMR = 1600 
    weeklength = 7

    #gets the past 7 days of progess if there is any...
    for i in range(weeklength):
        pastdate = str(datetime.now() - timedelta(days = i))
        push_st_date.append(pastdate[0:10])

    #sorting list to to make sure the dates are in correct order from left-right...
    push_st_date.sort(reverse=False)
    
    #logging actual user weight into graphs...
    for userweight in  user_stat_weight:
        totalcal = 0
        for date in push_st_date:
            if current_user.id == userweight.fk_id and str(userweight.Stat_DATE) == date:
                combine_date_weight[date] = userweight.Weight
    
    #to get data for the calories...
    for x in stat:
        for date in push_st_date:
            if current_user.id == x.fk__UserID and str(x.stat_Date) == date:
                cal_consumed_list[str(x.stat_Date)] = x.Total_Calories_Consumed
                cal_expended_list[str(x.stat_Date)] = x.total_Calories_expended

    print(calories_dict)

    return render_template('Statistics.html', name= current_user.name, 
    isLogin = isLog, labels = push_st_date, points = combine_date_weight, calories_consumed_chart = cal_consumed_list,
                calories_expended_chart = cal_expended_list)

@main.route('/workout')
def Workout():
    return render_template('Workout.html', isLogin = isLog)

@main.route('/about')
def about():
    return render_template('about.html', isLogin = isLog)


@main.route('/logExcsel', methods = ['POST'])
def logExercise():
    selExercise = request.form.get('selectedExercise')
    numMinutes = request.form.get('numMinutes')
    Exercise_list = Exercise.query.all()
    stats = Statistics.query.all()
    kg = 0.453592
    BMR = 1600

    print(str(selExercise))
    for exercise in Exercise_list:
        if exercise.Name == str(selExercise):
            p = exercise
        else:
            print('could not find the item')
    
    for stat in stats:
        if stat.fk__UserID == current_user.id and stat.stat_Date == today:
            stat.DailyWorkout.append(daily_workout(fk_Exercise_ID = p.Exercise_ID, minutes = numMinutes))
            stat.total_Calories_expended += (p.Calories_BURN * int(numMinutes))
            db.session.commit()
            return render_template('Workout.html', isLogin = isLog)


    new_stat_record = Statistics(stat_Date = date.today(),
            total_Calories_expended = (p.Calories_BURN * int(numMinutes) + BMR), 
            Total_Calories_Consumed = 0)   
    new_stat_record.DailyWorkout.append(daily_workout(fk_Exercise_ID = p.Exercise_ID, minutes = numMinutes, isLogin = isLog))
    
    
    current_user.Statistics.append(new_stat_record)
    db.session.add(new_stat_record)
    db.session.commit()       
    
    return render_template('Workout.html', isLogin = isLog)



@main.route('/logfoodsel', methods = ['POST'])
def logfoodselection():
    
    intial_item = request.form.get('Meal')
    stats = Statistics.query.all()
    food_list = Food.query.all()
    BMR = 1600
    gotitem = ''

    for items in food_list:
        if items.Display_name == intial_item:
            gotitem = items
            print(gotitem.Display_name)
    

    for stat in stats:
        if stat.fk__UserID == current_user.id and stat.stat_Date == today:
            stat.LoggedFood.append(logged_food(fk_Food_Index = gotitem.index_id))
            stat.Total_Calories_Consumed += gotitem.Calories
            db.session.commit()
            return render_template('Workout.html', isLogin = isLog)
        
    new_stat_record = Statistics(stat_Date = date.today(),
                        total_Calories_expended = BMR, Total_Calories_Consumed = gotitem.Calories)

    #extends the relationship between the User and Statistics class and commits it to the db...
    new_stat_record.LoggedFood.append(logged_food(fk_Food_Index = gotitem.index_id))
    current_user.Statistics.append(new_stat_record)
    db.session.add(new_stat_record)
    db.session.commit()

    return render_template('Workout.html', isLogin = isLog)


@main.route('/workout/inputFood', methods = ['POST'])
def getFoodItems():
    foods = request.form.get('FoodItms')
    item_list = Food.query.all()

    if foods:
        food_list = list(foods.split(','))
    else:
        food_list = []
    food_output_list = {}

    for item in item_list:
        for food in food_list:
            if re.search(food.lower(), item.Display_name):
                food_output_list[item.Display_name] = item.Calories
                break
    return render_template('FoodSelection.html', food= food_output_list, isLogin = isLog)


@main.route('/workout/inputFood/NewFoodItem', methods = ['POST'])
def inputNFoodInfo():
    return render_template('newFoodItem.html', isLogin = isLog)


@main.route('/workout/inputFood/NewFoodItem/postFoodItem', methods = ['POST'])
def postFoodItem():
    foodName = request.form.get('foodName')
    foodCal = request.form.get('calories')
    foods = Food.query.all()
    new_food_item = Food(Display_name = foodName.lower(), Calories = float(foodCal))


    db.session.add(new_food_item)
    db.session.commit()

    return render_template('Workout.html', isLogin = isLog)


@main.route('/workout/inputworkout', methods = ['POST'])
def inputExercise():
    exercise = request.form.get('excItms')
    exc_list = Exercise.query.all()
    show_exc_list = {}
    kg = 0.453592


    if exercise:
        user_exc_list = list(exercise.split(','))
    else:
        user_exc_list = []
        show_exc_list = {}

    for x in exc_list:
        for item in user_exc_list:
            print(item.lower(), '   ', x.Name)
            if re.search(x.Name, item):
                mets_formula = (x.Calories_BURN * 3.5 * (current_user.weight * kg)/ 200)
                show_exc_list[x.Name] = round(mets_formula, 2)
                break

    return render_template('inputworkout.html', exc_list = show_exc_list, isLogin = isLog)


@main.route('/workout/inputworkout/NewExercise', methods = ['POST'])
def ExcInfo():
    return render_template('NewExercise.html', isLogin = isLog)


@main.route("/workout/inputworkout/NewExercise/postExcItem", methods = ['POST'])
def NewExcItem():
    exercise = request.form.get('exercise')
    description = request.form.get('description')
    mets = request.form.get('Mets')


    new_exercise = Exercise(Description = description, Name = exercise.lower(), Calories_BURN = mets)

    db.session.add(new_exercise)
    db.session.commit()

    return render_template('Workout.html', isLogin = isLog)



@main.route("/workout/LogWeight", methods = ['POST'])
@login_required
def logWeight():
    weight = request.form.get('weight')
    user_weight = int(weight)
    statWeight_list = stat_weight.query.all()
    
    
    for stat in statWeight_list:
        if current_user.id == stat.fk_id and today == stat.Stat_DATE:
            stat.Weight = user_weight
            current_user.weight = user_weight
            db.session.commit()
            return render_template('Workout.html', isLogin = isLog)

    new_weight_record = stat_weight(Stat_DATE = date.today(), Weight = user_weight)

    #extends the relationship between the User and stat_weight class and commits it to the db...
    current_user.stat_weight.append(new_weight_record)
    db.session.add(new_weight_record)
    db.session.commit()

api/templates/FoodSelection.html
{% extends "base.html" %}


{%block content%}
<div class = "container is-centered">
    <h1>Choose the entree/snack you have eaten.</h1>
</div>
<form method='POST' action='/logfoodsel'>
    <div class ="field has-addons">
        <div class="control is-expanded">
            <div class = "select is-fullwidth">
                <select name="Meal">
                {%for items,cal in food.items()%}
                    <option >{{items}} </option>
                {%endfor%}
                </select>
            </div>
        </div>
    <div class="control">
        <button type="submit" class="button is-primary">Submit</button>
    </div>
</div>
</form>


<div class="select is-multiple">
    <select multiple size="8">
        {%for items,cal in food.items()%}
        <option >{{items}} calories: {{cal}} </option>
    {%endfor%}
    </select>
  </div>

<form method = "POST" action="/workout/inputFood/NewFoodItem">
    <div class= "message is-grouped level-item has-text-centered is-medium">
      <h2>Create New Food item if you don't find it above.
      </h2>
    </div>

    </article>
    <div class="column is-2  is-offset-5 level-item has-text-centered">
      <button onclick="hidebutton()" class="button is-block is-info is-medium is-fullwidth">New Food item
    </button>
  </div>
  </form>



{%endblock%}

api/templates/NewExercise.html
{% extends "base.html" %}

{%block content%}

<div class="columns">
    <div class = "column is-full">
        <h2 class = "column is-full">New Exercise</h2>
    </div>
</div>
<form method = "POST" action = "/workout/inputworkout/NewExercise/postExcItem">
    <div class= "field">
        <label class="label">Exercise</label>
        <div class ='control'>
        <input class="input column is-half"  name="exercise" type="text" placeholder= "Name of Exercise">
        </div>
        <label class="label">Description</label>
        <div class ='control'>
        <input class="input column is-half" name = "description" type="text" placeholder= "Description of Exercise">
        </div>
        <label class="label">Mets</label>
        <div class ='control'>
            <input class="input column is-half" name = "Mets" type="text" 
            placeholder= "How many METS does it burn. Example: vigrous activities set METs to 6. use whole numbers. moderate acitivty set mets to 4.">
        </div>
            <button onclick="hidebutton()" class="button is-block is-info is-medium">Submit
        </button>
    </div>
</form>


{% endblock %}

api/templates/Profile.html
{% extends "base.html" %}

{% block content %}
<div class= "columns">
  <div class="column">
    <div class = "content level-left mt-4">
      <h1 >{{name.name}}'s Profile</h1>
    </div> 
      <div class="control column is-half">
        <div class = "content">
          <h2>Name</h2>
          <input id = "name" class="column input" type="text" placeholder={{name.name}} reandonly disabled>
        </div>
      </div>
      <div class="control column is-half">
        <div class = "content">
          <h2>Email</h2>
          <input id = "name2" class="column input" type="text" placeholder={{name.email}} reandonly disabled>
        </div>
      </div>
      <div class="control column is-1">
        <div class = "content">
          <h2>Current Weight</h2>
          <input id = "name3" class="column input" type="text" placeholder={{name.weight}} reandonly disabled>
        </div>
      </div>
  </div>
</div>
<script src="{{url_for('static', filename='js/swapbuttons.js')}}"></script>

<div class ="content is-medium">
  <h1 class ="level-item has-text-centered">{{ name.name }}'s Daily Statistics</h1>
  </div>
  <div class = 'columns'>
    <div class="column content is-3 is-offset-1">
      <h1>Weight Status</h1>
      <canvas id="lineChart" width ="700" height ="500"></canvas>

      <script>
        var ctx = document.getElementById('lineChart').getContext("2d");
        var lineChart = new Chart(ctx, {
          type: "line",
          data: {
            labels: {{ labels | safe }},
            datasets: [
              {
                label: "Weight lbs",
                data: {{ points | safe }},
                fill: false,
                borderColor: "rgb(75, 192, 192)",
                lineTension: 0.1
              }
            ]
          },
          options: {
            responsive: false,
            scales: {
              y: {
                  beginAtZero: true,
                  suggestedMax: 300
              }
          }
            
          }
        });

      </script>
    </div>
      <div class = "column is-10 content is-large ml-6">

          <div class = 'column is-10 is-offset-2'>
            <h2 class= "content">Calories Status</h2>
          <canvas id="barChart" width = "700" height = "500"></canvas>
          <script>
            var ctx = document.getElementById('barChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: {{ labels | safe }},
                    datasets: [{
                        label: 'CALORIES CONSUMED',
                        data: {{calories_consumed_chart  | safe}},
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                        'rgba(255, 159, 64, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 99, 132, 1)'
                        ],
                        borderWidth: 1
                    },
                    {
                      label: 'CALORES EXPENDED',
                      data: {{ calories_expended_chart | safe }},
                      backgroundColor: [
                      'rgba(255, 159, 64, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 99, 132, 0.2)',
      
                      ],
                      borderColor: [
                          'rgba(255, 99, 132, 1)',
                          'rgba(54, 162, 235, 1)',
                          'rgba(255, 206, 86, 1)',
                          'rgba(75, 192, 192, 1)',
                          'rgba(153, 102, 255, 1)',
                          'rgba(255, 159, 64, 1)'
                      ],
                    }]
                },
                options: {
                    responsive: false,
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
          </script>
      </div>

  </div>
  
    
    </div>
  </div>

{% endblock %}

api/templates/Workout.html
{% extends "base.html" %}

{% block header %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/workout.css')}}">
{% endblock %}

{% block content %}
<article class = "message is-large">
<div class="level-item has-text-centered">
  <div class="message-header">
    Daily Workout info
  </div>
</div>
<form method = "POST" action="/workout/inputFood">
  <div class= "message is-grouped level-item has-text-centered is-medium">
    <h2>Enter multiple entree/food items to submit to log
      Note: Use comma to separate the items...
    </h2>
  </div>
  <div class= "columns level-item has-text-centered">
    <div class="column is-3 control">
      <textarea name="FoodItms" class="textarea" placeholder="Enter items, use submit button below to log food..."></textarea>
    </div>

  </article>
  <div class="column is-2  is-offset-5 level-item has-text-centered">
    <button onclick="hidebutton()" class="button is-block is-info is-medium is-fullwidth">Submit
  </button>
</div>
</form>

<form method = "POST" action="/workout/inputworkout">
  <div class= "message is-grouped level-item has-text-centered is-medium">
    <h2>Enter Exercises you have down in the session.
      Note: Use comma to separate the items...
    </h2>
  </div>
  <div class= "columns level-item has-text-centered">
    <div class="column is-3 control">
      <textarea name="excItms" class="textarea" placeholder="Enter items, use submit button below to log Exercise..."></textarea>
    </div>
</div>
  <div class="column is-2  is-offset-5 level-item has-text-centered">
    <button onclick="hidebutton()" class="button is-block is-info is-medium is-fullwidth">Submit
  </button>
</div>
</form>


<form method= "POST" action="/workout/LogWeight">
<div class = "message is-grouped level-item has-text-centered is-medium">
  Log Current Weight
</div>
<div class="columns level-item has-text-centered">
  <div class="column is-3 control">
    <input class="input is-medium" name="weight" type="text" placeholder="Enter Current Weight">
    <div class="column is-8  is-offset-2 level-item has-text-centered">
      <button onclick="hidebutton()" class="button is-block is-info is-medium is-fullwidth">Submit
    </button>
  </div>
  </div>

</div>

</form>

<form method = "POST" action='/workout/deletelogitem'>
  <div class = "message is-grouped level-item has-text-centered is-medium">
      Made a mistake logging an item?
  </div>
  <div class="column is-8  is-offset-2 level-item has-text-centered">
    <button onclick="hidebutton()" class="button is-block is-info is-medium is-fullwidth">Delete An Item
  </button>
</div>
</form>

{% endblock %}

api/templates/about.html
{% extends "base.html" %}

{% block content %}

<div class ="content is-medium">
  <h1 class ="level-item has-text-centered">Sample Statistics</h1>
  </div>
  <div class = 'columns'>
    <div class="column is-offset-1 is-half">

      <canvas id="lineChart" width ="900" height ="500"></canvas>
      <script>
        var ctx = document.getElementById('lineChart').getContext("2d");
        var lineChart = new Chart(ctx, {
          type: "line",
          data: {
            labels: ['2021-06-14','2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20'],
            datasets: [
              {
                label: "Weight lbs",
                data: [120, 150, 175, 180, 160, 135, 190],
                fill: false,
                borderColor: "rgb(75, 192, 192)",
                lineTension: 0.1
              }
            ]
          },
          options: {
            responsive: false,
            scales: {
              y: {
                  beginAtZero: true,
                  suggestedMax: 300
              }
          }
            
          }
        });

      </script>
    </div>
      <div class = "column is-one-quarter content is-large mt-6 mr-6">
        <h2>
          line-chart to help see progress in terms of meeting your weight goals
        </h2>
      </div>

  </div>
  <div class='columns is-vcentered'>
    <div class= "column is-one-quarter is-offset-1">
      <div class ="content is-medium">
      <h1>This Chart will help you look at the your calories consumed vs calories expended.
        Note: calories expended will be based on your level activity based on inital settings inputed
      </h1>
    </div>
    </div>
    <div class = 'column is-8 is-offset-1'>
    <canvas id="barChart" width = "1000" height = "500"></canvas>
    <script>
      var ctx = document.getElementById('barChart').getContext('2d');
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: ['2021-06-14','2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20'],
              datasets: [{
                  label: 'CALORIES CONSUMED',
                  data: [2000, 1600, 2675, 1987, 2125, 2354, 1600],
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(255, 159, 64, 0.2)'
                  ],
                  borderColor: [
                  'rgba(255, 159, 64, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 99, 132, 1)'
                  ],
                  borderWidth: 1
              },
              {
                label: 'CALORES EXPENDED',
                data: [3200, 2700, 2000, 1400, 3000, 1600, 2000],
                backgroundColor: [
                'rgba(255, 159, 64, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 99, 132, 0.2)',

                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
              }]
          },
          options: {
              responsive: false,
              scales: {
                  y: {
                      beginAtZero: true
                  }
              }
          }
      });
    </script>
    
    </div>
  </div>
  <div class="content">
    <h1>The various forms in the workout forms will help you Create, Update, and delete Exercises and meals.</h1>
      <h2>
        NOTE: ALL WORDS IN THE TEXT AREA WILL NEED TO BE SEPARATED BY A COMMA increase chance to find more items.
      </h2>
  </div>

{% endblock %}

api/templates/base.html
<!DOCTYPE html>
<html>
    <head>
      {%block head%}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-react-app"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
        <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/Home.css')}}">
        <script src= "https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js"></script>

        <title>PrimeFitness</title>
      {% endblock %}
    </head>


<body>
    <nav class="Nav">
        <div class="logo"><a href = "{{ url_for('main.index') }}">PrimeLifting</a></div>
        <div class = "NavBarLinks">
          <ul>
  
                <li><a href= "{{ url_for('main.profile') }}">Profile</a></li>
                <li><a href= "{{ url_for('main.about') }}">About</a></li>
                <li><a href= "{{ url_for('main.Workout') }}">Workout</a></li>
  
          </ul>
        </div>
        <div class = 'login1' onclick="hidebutton()">
          {%if isLogin == True %}
          <a id ='navlog' href= "{{ url_for('auth.logout') }}">Logout</a>
          {%else %}
            <a id ='navlog' href= "{{ url_for('auth.login') }}">Login</a>
            <a id = 'navlog' href= "{{ url_for('auth.signup') }}">Sign-Up</a>
            {%endif %}
        </div>
    </nav>


    {% block content %}

    {% endblock %}
    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>@Bently is free to use</strong>
      </div>
    </footer>
</body>

</html>

api/templates/index.html
{% extends "base.html" %}

{%block content%}
    <div>
        <div class= "bground">
          <div class = "BContent">
            <h1>WELCOME TO PRIME LIFTING</h1>
            <div class = 'login'>
              {%if isLogin %}
              <a id ='log' href= "{{ url_for('auth.logout') }}">Logout</a>
              {%else %}
                <a id ='log' href= "{{ url_for('auth.login') }}">Login</a>
                <a id = 'log' href= "{{ url_for('auth.signup') }}">Sign-Up</a>
              {%endif %}
            </div>
          </div>
        </div>
        <div class = "container">
          <div class ="card">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <div class = "content">
              <h2>01</h2>
              <h3>Objective</h3>
              <p>Learn more about why this site was created</p>
              <a href="{{ url_for('main.about') }}">Read More</a>
            </div>
          </div>
          <div class ="card">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <div class = "content">
              <h2>02</h2>
              <h3>Statistics</h3>
              <p>An overview of what we offer for you</p>
              <a href="{{ url_for('main.statistics') }}">Read More</a>
            </div>
          </div>
          <div class ="card">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <div class = "content">
              <h2>03</h2>
              <h3>Workout</h3>
              <p>find out how to log items in the Workout Page</p>
              <a href="{{ url_for('main.Workout') }}">Read More</a>
            </div>
          </div>
        </div>
      </div>

{% endblock %}
</html>

api/templates/newFoodItem.html
{% extends "base.html" %}
{% block content%}

<form method = "POST" action = "/workout/inputFood/NewFoodItem/postFoodItem">
    <div class= "field">
        <label class="label">Name of Food</label>
        <div class ='control'>
        <input class="input column is-half"  name="foodName" type="text" placeholder= "Name of Exercise">
        </div>
        <label class="label">Calories</label>
        <div class ='control'>
        <input class="input column is-half" name = "calories" type="text" placeholder= "Amount of calories in 1 serving">
        </div>
            <button onclick="hidebutton()" class="button is-block is-info is-medium">Submit
        </button>
    </div>
</form>

{% endblock %}